#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

ZUUL_USER_SSH_PUBLIC_KEY=${ZUUL_USER_SSH_PUBLIC_KEY:-$HOME/.ssh/id_rsa.pub}

if [ $ZUUL_USER_SSH_PUBLIC_KEY = $HOME/.ssh/id_rsa.pub ]; then
    if [ -f $ZUUL_USER_SSH_PUBLIC_KEY ]; then
        # save the public key inside the chroot from current user
        cat $ZUUL_USER_SSH_PUBLIC_KEY >> $TMP_HOOKS_PATH/zuul-user-ssh-public-key
    else
        die "Can not find public key for zuul user!"
    fi
else
    if [ -f $ZUUL_USER_SSH_PUBLIC_KEY ]; then
        # save the public key inside the chroot from specific file
        cat $ZUUL_USER_SSH_PUBLIC_KEY >> $TMP_HOOKS_PATH/zuul-user-ssh-public-key
    else
        # save the specific public key inside the chroot derectly
        echo "ssh-rsa $ZUUL_USER_SSH_PUBLIC_KEY" >> $TMP_HOOKS_PATH/zuul-user-ssh-public-key
    fi
fi
